import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by Foundry',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
